version: '3.9'

services:
  tomcat:
    image: tomcat:8
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps  # Montez vos applications JSP dans Tomcat
    environment:
      - POSTGRES_HOST=postgres
    command: ["/bin/sh", "-c", "rm -rf /usr/local/tomcat/work/Catalina/localhost && catalina.sh run"]

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  postgres:
    image: postgres:16
    shm_size: 128mb
    environment:
      POSTGRES_DB: volcanix
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeit

    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data  # Montez le dossier de données pour persistance
      - ./pg-init/init.sql:/docker-entrypoint-initdb.d/init.sql