---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl
spec:
  jobTemplate:
    spec:
      template:
        metadata: {}
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - curl http://volcanix/hello-metrics
              image: busybox:1.36
              imagePullPolicy: IfNotPresent
              name: curl
          restartPolicy: OnFailure
  schedule: '* * * * *'
