---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl
spec:
  jobTemplate:
    spec:
      template:
        metadata: {}
        spec:
          containers:
            - args:
                - http://volcanix/hello-metrics
              image: curlimages/curl:8.10.1
              imagePullPolicy: IfNotPresent
              name: curl
          restartPolicy: OnFailure
  schedule: '* * * * *'
