---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.14.1
    app.quarkus.io/commit-id: ddaec899aa5af4f3fd4b15a4d90c14cd577939b8
    app.quarkus.io/vcs-uri: https://github.com/zepouet/demo-volcamp.git
    app.quarkus.io/build-timestamp: 2024-09-21 - 08:11:31 +0000
  labels:
    app.kubernetes.io/name: volcanix
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: volcanix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: volcanix
      app.kubernetes.io/version: 1.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.14.1
        app.quarkus.io/commit-id: ddaec899aa5af4f3fd4b15a4d90c14cd577939b8
        app.quarkus.io/vcs-uri: https://github.com/zepouet/demo-volcamp.git
        app.quarkus.io/build-timestamp: 2024-09-21 - 08:11:31 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: volcanix
        app.kubernetes.io/version: 1.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          name: volcanix
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
