---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.14.1
    app.quarkus.io/commit-id: fed22e98dd2ff42224ee8cb314501ceed8670af3
    app.quarkus.io/vcs-uri: https://github.com/zepouet/demo-volcamp.git
    app.quarkus.io/build-timestamp: 2024-09-23 - 20:00:34 +0000
  labels:
    app.kubernetes.io/name: volcanix
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: volcanix
spec:
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - backend:
              service:
                name: volcanix
                port:
                  name: http
            path: /
            pathType: Prefix
