apiVersion: autoscaling.x-k8s.io/v1alpha1
kind: StartupCPUBoost
metadata:
  name: boost
  namespace: remi
selector:
  matchExpressions:
  - key: app.kubernetes.io/name
    operator: In
    values:
      - "stress"
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: stress
      percentageIncrease:
        value: 200
  durationPolicy:
    fixedDuration:
      unit: Seconds
      value: 60