apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: stress
  name: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stress
    spec:
      containers:
      - image: progrium/stress
        args: ["--cpu", "1"]
        name: stress
        resources:
          limits:
            cpu: 100m