apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:8.10.1
              imagePullPolicy: IfNotPresent
              args:
                - http://volcanix/hello-metrics
          restartPolicy: OnFailure