name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: java -version
      - run: uname -a
      - name: Generate binary
        run: |
          cd 02-quarkus
          ./mvnw -B clean package -Dnative -DskipTests
        env:
          NO_DOCKER: true
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: /target/qute-quickstart-1.0.1-SNAPSHOT-native-image-source-jar/qute-quickstart-1.0.1-SNAPSHOT-runner
          path: qute-quickstart-1.0.1-SNAPSHOT-runner
