name: Linux family - GraalVM Native binary
on:
  push:
    paths:
      - .github/workflows/graalvm-linux.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-linux
  cancel-in-progress: true
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    #runs-on: self-hosted
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          #distribution: 'liberica' # See 'Options' section below for all available distributions
          #distribution: 'graalvm' # See 'Options' section below for all available distributions
          distribution: 'mandrel' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: java -version
      - run: uname -a
      - name: Generate binary
        run: |
          cd 02-quarkus
          ./mvnw -B -ntp clean package -Dnative -DskipTests
        env:
          NO_DOCKER: true
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: volcanix-linux
          path: 02-quarkus/target/qute-quickstart-1.0.1-SNAPSHOT-runner
