name: Image x86
on:
  push:
    paths:
      - .github/workflows/image-x86.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-image-x86
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    #runs-on: self-hosted
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java -version
      - run: uname -a
      - name: Build Container image
        run: |
          cd 02-quarkus
          ./mvnw clean package -DskipTests \
                    -Dquarkus.docker.buildx.platform=linux/amd64 \
                    -Dquarkus.container-image.build=true \
                    -Dquarkus.container-image.push=true \
                    -Dquarkus.container-image.group=${{ env.IMAGE_NAME }} \
                    -Dquarkus.container-image.username=${{ github.actor }} \
                    -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }} \
                    -Dquarkus.container-image.registry=${{ env.REGISTRY }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update k8s resources"