# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/aarch64]
    
    defaults:
      run:
        shell: bash
        working-directory: ./02-quarkus

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: maven
    - name: Generate Container image
      run: "./mvnw -B clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.docker.buildx.platform=${{ matrix.platform }}"